services:
  - type: web
    name: hub-dashboard
    env: node
    plan: starter
    buildCommand: ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_DIR
        value: uploads
      # These need to be set manually in Render dashboard:
      # - SUPABASE_URL
      # - SUPABASE_ANON_KEY
      # - SUPABASE_SERVICE_ROLE_KEY
      # - FRONTEND_URL (will be your Render app URL)
